#!/usr/bin/env python3
"""Generate Stage-1 task-node role descriptions for KDD pilot samples.

This is the KDD-local version of the older role-description scripts. It reads
the stage1 pilot JSONL files, treats filtered paper FoS entries as preliminary
task nodes, writes one prompt per paper, and optionally calls an LLM to produce
one role description per node.

Default behavior is dry-run prompt generation only. Add --generate to call the
configured backend.
"""

from __future__ import annotations

import argparse
import difflib
import json
import os
import re
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Sequence


DEFAULT_SAMPLE_JSONL = "outputs/stage1_pilot_samples/smoke_200.jsonl"
DEFAULT_OUT_DIR = "outputs/stage1_task_node_role_descriptions_smoke_200"


def load_dotenv() -> None:
    for directory in [Path.cwd(), *Path.cwd().parents]:
        paths = [directory / name for name in (".env", ".env.openai", ".env.together")]
        existing = [path for path in paths if path.exists()]
        if not existing:
            continue
        for path in existing:
            with path.open("r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#") or "=" not in line:
                        continue
                    key, value = line.split("=", 1)
                    key = key.strip()
                    value = value.strip().strip('"').strip("'")
                    if key and key not in os.environ:
                        os.environ[key] = value
        return


def parse_args() -> argparse.Namespace:
    load_dotenv()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sample-jsonl", default=DEFAULT_SAMPLE_JSONL)
    parser.add_argument("--out-dir", default=DEFAULT_OUT_DIR)
    parser.add_argument("--limit", type=int, default=0, help="0 means all papers")
    parser.add_argument(
        "--max-nodes-per-paper",
        type=int,
        default=0,
        help="Maximum FoS nodes per paper. Use 0 for no cap.",
    )
    parser.add_argument("--min-fos-weight", type=float, default=0.4)
    parser.add_argument(
        "--node-scope",
        choices=("direct", "expanded"),
        default="direct",
        help="direct keeps the original prompt behavior; expanded adds root and all FoS ancestors.",
    )
    parser.add_argument(
        "--expanded-node-policy",
        choices=("all_ancestors", "minimal_tree"),
        default="all_ancestors",
        help=(
            "Only used with --node-scope expanded. all_ancestors keeps every direct FoS ancestor; "
            "minimal_tree adds only the connector ancestors needed to link direct FoS nodes into a compact tree."
        ),
    )
    parser.add_argument("--fos-map", default="../data/dblp/FieldsOfStudy.txt")
    parser.add_argument("--taxonomy-edges", default="../data/dblp/13.FieldOfStudyChildren.nt")
    parser.add_argument(
        "--ancestor-min-covered-direct",
        type=int,
        default=1,
        help=(
            "Only used with --node-scope expanded. Keep non-direct ancestor nodes "
            "that cover at least this many direct FoS descendants. Direct nodes and root are always kept."
        ),
    )
    parser.add_argument(
        "--include-root-role",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Only used with --node-scope expanded. Include a root role generated by the LLM.",
    )
    parser.add_argument(
        "--expanded-prompt-variant",
        choices=(
            "v2_boundary",
            "retrieval_dense",
            "keyword_query",
            "balanced_recall",
            "top1_recall_diverse",
            "evidence_facets",
            "direct_style",
            "v3_retrieval",
        ),
        default="v2_boundary",
        help=(
            "Only used with --node-scope expanded. v2_boundary preserves the original expanded prompt; "
            "the other variants tune role text for expert-embedding retrieval."
        ),
    )
    parser.add_argument(
        "--generate",
        action="store_true",
        help="Call the LLM. Without this flag, only prompts are written.",
    )
    parser.add_argument("--backend", choices=("together", "openai", "template"), default="together")
    parser.add_argument("--model", default="openai/gpt-oss-120b")
    parser.add_argument("--api-key", default="")
    parser.add_argument("--temperature", type=float, default=0.0)
    parser.add_argument("--max-tokens", type=int, default=8192)
    parser.add_argument("--retry", type=int, default=3)
    parser.add_argument("--retry-sleep", type=float, default=2.0)
    parser.add_argument("--sleep-seconds", type=float, default=0.0)
    parser.add_argument("--workers", type=int, default=1)
    parser.add_argument("--progress-every", type=int, default=1)
    return parser.parse_args()


def iter_jsonl(path: Path) -> Iterable[dict]:
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                yield json.loads(line)


def reconstruct_abstract(indexed_abstract: object) -> str:
    if not isinstance(indexed_abstract, dict):
        return ""
    inverted = indexed_abstract.get("InvertedIndex")
    if not isinstance(inverted, dict):
        return ""
    try:
        length = int(indexed_abstract.get("IndexLength") or 0)
    except (TypeError, ValueError):
        length = 0
    positions: Dict[int, str] = {}
    for token, raw_indices in inverted.items():
        if not isinstance(raw_indices, list):
            continue
        for raw_idx in raw_indices:
            try:
                positions[int(raw_idx)] = str(token)
            except (TypeError, ValueError):
                continue
    if length <= 0:
        length = max(positions, default=-1) + 1
    return " ".join(positions.get(idx, "") for idx in range(length)).strip()


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")
    return slug or "node"


def canonical_name(value: str) -> str:
    return re.sub(r"\s+", " ", value.strip().lower())


def load_fos_maps(path: Path) -> tuple[dict[str, str], dict[str, str], dict[str, int]]:
    name_to_id: dict[str, str] = {}
    id_to_name: dict[str, str] = {}
    id_to_level: dict[str, int] = {}
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 4:
                continue
            fos_id = parts[0].strip()
            try:
                level = int(parts[1])
            except (TypeError, ValueError):
                level = -1
            norm_name = parts[2].strip()
            display_name = parts[3].strip()
            if not fos_id:
                continue
            label = display_name or norm_name or fos_id
            id_to_name[fos_id] = label
            id_to_level[fos_id] = level
            if norm_name:
                name_to_id[canonical_name(norm_name)] = fos_id
            if display_name:
                name_to_id[canonical_name(display_name)] = fos_id
    return name_to_id, id_to_name, id_to_level


ENTITY_RE = re.compile(r"/entity/(\d+)>")


def load_child_to_parents(path: Path) -> dict[str, set[str]]:
    child_to_parents: dict[str, set[str]] = {}
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            ids = ENTITY_RE.findall(line)
            if len(ids) < 2:
                continue
            child, parent = ids[0], ids[1]
            if child != parent:
                child_to_parents.setdefault(child, set()).add(parent)
    return child_to_parents


def ancestor_distances(node_id: str, child_to_parents: Mapping[str, set[str]]) -> dict[str, int]:
    distances: dict[str, int] = {}
    frontier = {node_id}
    seen = {node_id}
    depth = 0
    while frontier:
        depth += 1
        next_frontier: set[str] = set()
        for child in frontier:
            for parent in child_to_parents.get(child, set()):
                if parent in seen:
                    continue
                seen.add(parent)
                distances[parent] = depth
                next_frontier.add(parent)
        frontier = next_frontier
    return distances


def shortest_parent_paths(node_id: str, child_to_parents: Mapping[str, set[str]]) -> dict[str, list[str]]:
    paths: dict[str, list[str]] = {node_id: [node_id]}
    frontier = [node_id]
    for child in frontier:
        for parent in sorted(child_to_parents.get(child, set())):
            if parent in paths:
                continue
            paths[parent] = [*paths[child], parent]
            frontier.append(parent)
    return paths


def minimal_connector_paths(
    direct_fos_ids: Sequence[str],
    child_to_parents: Mapping[str, set[str]],
) -> dict[str, list[str]]:
    numeric_ids = [node_id for node_id in direct_fos_ids if not node_id.startswith("slug::")]
    if not numeric_ids:
        return {}
    path_maps = {node_id: shortest_parent_paths(node_id, child_to_parents) for node_id in numeric_ids}

    direct_sets = {node_id: set(paths) for node_id, paths in path_maps.items()}
    neighbors: dict[str, set[str]] = {node_id: set() for node_id in numeric_ids}
    for idx, left in enumerate(numeric_ids):
        for right in numeric_ids[idx + 1 :]:
            if direct_sets[left] & direct_sets[right]:
                neighbors[left].add(right)
                neighbors[right].add(left)

    components: list[list[str]] = []
    seen: set[str] = set()
    for node_id in numeric_ids:
        if node_id in seen:
            continue
        stack = [node_id]
        seen.add(node_id)
        component: list[str] = []
        while stack:
            current = stack.pop()
            component.append(current)
            for neighbor in sorted(neighbors[current]):
                if neighbor in seen:
                    continue
                seen.add(neighbor)
                stack.append(neighbor)
        components.append(sorted(component))

    selected: dict[str, list[str]] = {}

    def candidate_key(candidate: str, component: Sequence[str]) -> tuple[int, int, str]:
        selected_paths = [path_maps[node_id][candidate] for node_id in component]
        union_nodes = {path_node for path in selected_paths for path_node in path}
        total_hops = sum(len(path) - 1 for path in selected_paths)
        return (len(union_nodes), total_hops, candidate)

    for component in components:
        if len(component) == 1:
            selected[component[0]] = [component[0]]
            continue
        common_ancestors: set[str] | None = None
        for node_id in component:
            nodes = direct_sets[node_id]
            common_ancestors = nodes if common_ancestors is None else common_ancestors & nodes
        if common_ancestors:
            best_connector = min(common_ancestors, key=lambda candidate: candidate_key(candidate, component))
            for node_id in component:
                selected[node_id] = path_maps[node_id][best_connector]
            continue

        coverage: dict[str, set[str]] = {}
        component_set = set(component)
        for node_id in component:
            for candidate in path_maps[node_id]:
                covered = coverage.setdefault(candidate, set())
                covered.add(node_id)
        shared_candidates = {
            candidate
            for candidate, covered in coverage.items()
            if len(covered & component_set) >= 2
        }
        for node_id in component:
            local_candidates = shared_candidates & set(path_maps[node_id])
            if not local_candidates:
                selected[node_id] = [node_id]
                continue
            best_connector = min(
                local_candidates,
                key=lambda candidate: (
                    len(path_maps[node_id][candidate]) - 1,
                    -len(coverage[candidate] & component_set),
                    candidate,
                ),
            )
            selected[node_id] = path_maps[node_id][best_connector]

    return selected


def extract_nodes(
    obj: dict,
    max_nodes: int,
    min_weight: float,
) -> List[dict]:
    fos_items = obj.get("fos") or []
    candidates: List[dict] = []
    seen_names: set[str] = set()
    for item in fos_items:
        if not isinstance(item, dict):
            continue
        name = str(item.get("name", "")).strip()
        if not name or name.lower() in seen_names:
            continue
        seen_names.add(name.lower())
        try:
            weight = float(item.get("w", item.get("weight", 0.0)) or 0.0)
        except (TypeError, ValueError):
            weight = 0.0
        if weight < min_weight:
            continue
        candidates.append(
            {
                "node_id": f"fos::{slugify(name)}",
                "node_name": name,
                "node_level": "fos",
                "node_weight": weight,
            }
        )
    candidates.sort(key=lambda row: (-row["node_weight"], row["node_name"].lower()))
    if max_nodes > 0:
        return candidates[:max_nodes]
    return candidates


def extract_expanded_nodes(
    obj: dict,
    max_nodes: int,
    min_weight: float,
    name_to_fos_id: Mapping[str, str],
    id_to_name: Mapping[str, str],
    id_to_level: Mapping[str, int],
    child_to_parents: Mapping[str, set[str]],
    include_root_role: bool,
    ancestor_min_covered_direct: int,
    expanded_node_policy: str,
) -> List[dict]:
    direct_nodes = extract_nodes(obj, max_nodes=max_nodes, min_weight=min_weight)
    expanded: dict[str, dict] = {}
    if include_root_role:
        expanded["__root__"] = {
            "node_id": "__root__",
            "node_name": "Whole paper",
            "node_level": "root",
            "node_weight": 1.0,
            "is_root": True,
            "is_direct": False,
            "ancestor_depth": 0,
            "tree_parent_node_ids": [],
            "direct_descendant_node_ids": [],
            "direct_descendant_node_names": [],
        }

    direct_fos_ids: list[str] = []
    direct_by_id: dict[str, dict] = {}
    for node in direct_nodes:
        fos_id = name_to_fos_id.get(canonical_name(str(node["node_name"])))
        if not fos_id:
            fos_id = f"slug::{node['node_id']}"
        direct_fos_ids.append(fos_id)
        direct_by_id[fos_id] = node
        expanded[fos_id] = {
            "node_id": fos_id,
            "node_name": id_to_name.get(fos_id, node["node_name"]),
            "node_level": id_to_level.get(fos_id, "fos"),
            "node_weight": node["node_weight"],
            "is_root": False,
            "is_direct": True,
            "ancestor_depth": 0,
            "tree_parent_node_ids": [],
            "direct_descendant_node_ids": [fos_id],
            "direct_descendant_node_names": [str(node["node_name"])],
        }

    if expanded_node_policy == "minimal_tree":
        selected_paths = minimal_connector_paths(direct_fos_ids, child_to_parents)
        for direct_fos_id, path in selected_paths.items():
            direct_node = direct_by_id[direct_fos_id]
            for depth, node_id in enumerate(path):
                row = expanded.setdefault(
                    node_id,
                    {
                        "node_id": node_id,
                        "node_name": id_to_name.get(node_id, node_id),
                        "node_level": id_to_level.get(node_id, "fos"),
                        "node_weight": 0.0,
                        "is_root": False,
                        "is_direct": False,
                        "ancestor_depth": depth,
                        "tree_parent_node_ids": [],
                        "direct_descendant_node_ids": [],
                        "direct_descendant_node_names": [],
                    },
                )
                row["node_weight"] = max(float(row.get("node_weight") or 0.0), float(direct_node["node_weight"]))
                current_depth = row.get("ancestor_depth")
                row["ancestor_depth"] = min(int(current_depth), depth) if current_depth is not None else depth
                if depth + 1 < len(path) and path[depth + 1] not in row["tree_parent_node_ids"]:
                    row["tree_parent_node_ids"].append(path[depth + 1])
                if direct_fos_id not in row["direct_descendant_node_ids"]:
                    row["direct_descendant_node_ids"].append(direct_fos_id)
                    row["direct_descendant_node_names"].append(str(direct_node["node_name"]))
        if include_root_role:
            for row in expanded.values():
                if row.get("is_root") or row.get("tree_parent_node_ids"):
                    continue
                row["tree_parent_node_ids"] = ["__root__"]
    else:
        for direct_fos_id in direct_fos_ids:
            if direct_fos_id.startswith("slug::"):
                continue
            direct_node = direct_by_id[direct_fos_id]
            for ancestor_id, depth in ancestor_distances(direct_fos_id, child_to_parents).items():
                row = expanded.setdefault(
                    ancestor_id,
                    {
                        "node_id": ancestor_id,
                        "node_name": id_to_name.get(ancestor_id, ancestor_id),
                        "node_level": id_to_level.get(ancestor_id, "fos"),
                        "node_weight": 0.0,
                        "is_root": False,
                        "is_direct": False,
                        "ancestor_depth": depth,
                        "tree_parent_node_ids": [],
                        "direct_descendant_node_ids": [],
                        "direct_descendant_node_names": [],
                    },
                )
                row["node_weight"] = max(float(row.get("node_weight") or 0.0), float(direct_node["node_weight"]))
                current_depth = row.get("ancestor_depth")
                row["ancestor_depth"] = min(int(current_depth), depth) if current_depth is not None else depth
                if direct_fos_id not in row["direct_descendant_node_ids"]:
                    row["direct_descendant_node_ids"].append(direct_fos_id)
                    row["direct_descendant_node_names"].append(str(direct_node["node_name"]))

    rows = [
        row
        for row in expanded.values()
        if row.get("is_root")
        or row.get("is_direct")
        or len(row.get("direct_descendant_node_ids") or []) >= ancestor_min_covered_direct
    ]
    rows.sort(
        key=lambda row: (
            0 if row.get("is_root") else 1,
            int(row.get("ancestor_depth") or 0),
            0 if row.get("is_direct") else 1,
            str(row.get("node_name") or "").lower(),
        )
    )
    return rows


def title_abstract(obj: dict) -> str:
    title = str(obj.get("title", "")).strip()
    abstract = str((obj.get("stage1_sample") or {}).get("abstract") or "").strip()
    if not abstract:
        abstract = str(obj.get("abstract") or "").strip()
    if not abstract:
        abstract = reconstruct_abstract(obj.get("indexed_abstract"))
    if title and abstract:
        return f"Title: {title}\nAbstract: {abstract}"
    return title or abstract


def system_prompt() -> str:
    return (
        "You generate JSON node-specific research expertise profiles for "
        "research team formation. Return only valid JSON."
    )


def build_prompt(paper_id: str, text: str, nodes: Sequence[dict]) -> str:
    node_lines = "\n".join(
        f"{node['node_id']} | {node['node_name']} | {node['node_level']}"
        for node in nodes
    )
    return f"""You are analyzing a research paper as a team-formation task.

You are given a paper (title + abstract) and a LIST of taxonomy nodes
for this paper. For EACH node, write a short node-specific research-
expertise paragraph describing the SINGLE technical facet of this paper
that this node is responsible for. The paragraphs will be embedded and
compared against experts' historical paper embeddings -- write in a
paper-like research-expertise style, and make the paragraphs
DISCRIMINATE between nodes.

Paper id: {paper_id}
Title/abstract:
{text}

Taxonomy nodes (id | name | level):
{node_lines}

REQUIREMENTS:
1. ONE FACET PER NODE. Each paragraph covers only the part of the paper
   tied to this node. Never restate the whole paper in every node.
2. NODES MUST DIFFER. No two paragraphs should be near-identical. Use the
   fact that you see all nodes at once to push each toward a distinct facet.
3. A broad/high-level node must NOT absorb the content of its more specific
   siblings. If a node is broad, describe the paper's facet at the level of
   generality that node actually owns -- do not pull in sibling specifics.
4. evidence_from_abstract: 1-3 short spans. Prefer non-overlapping sentences
   or clauses across nodes. If a sentence genuinely contains two concepts,
   two nodes may share it but must highlight different clauses/aspects.
5. Avoid phrases like "This task requires an expert who can".

OUTPUT -- JSON array, one object per node:
{{ paper_id, node_id, role_description, key_capabilities, evidence_from_abstract }}

Return the JSON array in exactly the same node order as the input list."""


def expanded_node_lines(nodes: Sequence[dict]) -> str:
    return "\n".join(
        (
            f"{idx + 1}. {node['node_id']} | {node['node_name']} "
            f"| root={int(bool(node.get('is_root')))} | direct={int(bool(node.get('is_direct')))} "
            f"| ancestor_depth={node.get('ancestor_depth', '')} "
            f"| tree_parent_ids={json.dumps(node.get('tree_parent_node_ids') or [], ensure_ascii=False)} "
            f"| covered_direct_fos={json.dumps(node.get('direct_descendant_node_names') or [], ensure_ascii=False)}"
        )
        for idx, node in enumerate(nodes)
    )


def expanded_output_schema() -> str:
    return """OUTPUT -- JSON array, one object per node:
{
  "paper_id": "...",
  "node_id": "...",
  "role_description": "...",
  "key_capabilities": ["...", "..."],
  "evidence_from_abstract": ["...", "..."],
  "subtree_scope": "whole_paper | direct_fos | ancestor_subtree",
  "covered_direct_fos": ["..."],
  "distinctive_boundary": "How this role differs from parent/children/siblings"
}

Return only valid JSON."""


def build_expanded_prompt_v2_boundary(paper_id: str, text: str, nodes: Sequence[dict]) -> str:
    node_lines = "\n".join(
        (
            f"{idx + 1}. {node['node_id']} | {node['node_name']} "
            f"| root={int(bool(node.get('is_root')))} | direct={int(bool(node.get('is_direct')))} "
            f"| ancestor_depth={node.get('ancestor_depth', '')} "
            f"| tree_parent_ids={json.dumps(node.get('tree_parent_node_ids') or [], ensure_ascii=False)} "
            f"| covered_direct_fos={json.dumps(node.get('direct_descendant_node_names') or [], ensure_ascii=False)}"
        )
        for idx, node in enumerate(nodes)
    )
    return f"""You are analyzing a research paper as a hierarchical team-formation task.

You are given a paper (title + abstract) and an EXPANDED paper-local taxonomy.
The taxonomy nodes include:
- __root__: the whole-paper role.
- Direct FoS nodes observed on the paper.
- Ancestor FoS nodes that cover one or more direct FoS descendants.

For EACH node, write a paper-specific research role description for the subtree
rooted at that node. The text will be embedded and matched to experts' historical
paper embeddings. Make each role useful for distinguishing which expert should
own that subtree. Do NOT decide the final partition; a later model will cut the
tree into responsibility regions.

Paper id: {paper_id}
Title/abstract:
{text}

Expanded taxonomy nodes in required output order:
{node_lines}

REQUIREMENTS:
1. Return exactly one JSON object for every input node, in the same order.
2. The __root__ role should summarize the paper's overall research contribution
   as a whole-task expert need, not merely restate the title.
3. A direct FoS role should focus on the specific technical facet attached to
   that direct FoS.
4. An ancestor FoS role should synthesize only its listed covered_direct_fos
   descendants into a coherent subtree responsibility. It must not absorb
   unrelated sibling subtrees.
5. The taxonomy may contain noisy or overly broad ancestor labels. Do NOT invent
   an application domain or technical topic solely from an ancestor node name.
   If an ancestor name is not directly supported by the title/abstract, write a
   conservative role grounded in the covered_direct_fos descendants and the
   paper evidence; keep evidence_from_abstract empty if there is no supporting
   span for the ancestor label itself.
6. Roles must be distinct across siblings and across parent/child nodes. The
   parent should describe the broader shared responsibility; the child should
   retain its narrower technical responsibility.
7. Avoid generic phrases such as "This task requires an expert who can".
8. evidence_from_abstract should contain 1-3 short spans or clauses from the
   title/abstract. Use an empty list only when the abstract is unavailable.

{expanded_output_schema()}"""


def build_expanded_prompt_direct_style(paper_id: str, text: str, nodes: Sequence[dict]) -> str:
    node_lines = "\n".join(
        f"{node['node_id']} | {node['node_name']} | {node.get('node_level', 'fos')}"
        for node in nodes
    )
    return f"""You are analyzing a research paper as a team-formation task.

You are given a paper (title + abstract) and a LIST of taxonomy nodes
for this paper. For EACH node, write a short node-specific research-
expertise paragraph describing the SINGLE technical facet of this paper
that this node is responsible for. The paragraphs will be embedded and
compared against experts' historical paper embeddings -- write in a
paper-like research-expertise style, and make the paragraphs
DISCRIMINATE between nodes.

Paper id: {paper_id}
Title/abstract:
{text}

Taxonomy nodes (id | name | level):
{node_lines}

REQUIREMENTS:
1. ONE FACET PER NODE. Each paragraph covers only the part of the paper
   tied to this node. Never restate the whole paper in every node.
2. NODES MUST DIFFER. No two paragraphs should be near-identical. Use the
   fact that you see all nodes at once to push each toward a distinct facet.
3. A broad/high-level node must NOT absorb the content of its more specific
   siblings. If a node is broad, describe the paper's facet at the level of
   generality that node actually owns -- do not pull in sibling specifics.
4. evidence_from_abstract: 1-3 short spans. Prefer non-overlapping sentences
   or clauses across nodes. If a sentence genuinely contains two concepts,
   two nodes may share it but must highlight different clauses/aspects.
5. Avoid phrases like "This task requires an expert who can".

OUTPUT -- JSON array, one object per node:
{{ paper_id, node_id, role_description, key_capabilities, evidence_from_abstract }}

Return the JSON array in exactly the same node order as the input list."""


def build_expanded_prompt_v3_retrieval(paper_id: str, text: str, nodes: Sequence[dict]) -> str:
    node_lines = "\n".join(
        (
            f"{idx + 1}. {node['node_id']} | {node['node_name']} "
            f"| root={int(bool(node.get('is_root')))} | direct={int(bool(node.get('is_direct')))} "
            f"| tree_parent_ids={json.dumps(node.get('tree_parent_node_ids') or [], ensure_ascii=False)} "
            f"| covered_direct_fos={json.dumps(node.get('direct_descendant_node_names') or [], ensure_ascii=False)}"
        )
        for idx, node in enumerate(nodes)
    )
    return f"""You are writing retrieval-optimized expert-role queries for a research
paper. These role descriptions will be embedded and matched against experts'
historical paper embeddings.

You are given a paper (title + abstract) and a compact paper-local taxonomy.
The taxonomy contains:
- __root__: one whole-paper retrieval query.
- Direct FoS nodes observed on the paper: primary retrieval queries.
- Connector/ancestor nodes: conservative subtree queries that combine only
  their listed covered_direct_fos descendants.

Your main objective is retrieval quality: write role_description text that is
likely to match historical papers by the right expert. Still keep the output
explainable by filling evidence_from_abstract, covered_direct_fos, and
distinctive_boundary.

Paper id: {paper_id}
Title/abstract:
{text}

Taxonomy nodes in required output order:
{node_lines}

ROLE_DESCRIPTION WRITING RULES:
1. Write role_description as a dense expert-profile search query, not as a
   prose explanation of the task. Use paper-specific technical nouns, methods,
   objects, datasets/evaluation terms, and common synonyms when they are
   supported by the title/abstract.
2. Start direct FoS role_description with the node name or a close synonym, then
   add the paper-specific problem/method context. Direct FoS nodes are the main
   retrieval surface; make them concrete and discriminative.
3. For __root__, write a whole-paper expert query covering the central problem,
   methods, technical objects, and evaluation/resource aspects. Do not merely
   restate the title.
4. For connector/ancestor nodes, write only the shared expertise needed for the
   listed covered_direct_fos descendants. If the ancestor label is broad or
   noisy, do not expand it into an unsupported field; anchor the text in the
   descendants and paper evidence.
5. Avoid generic phrases such as "This task requires an expert who can",
   "responsible for", "subtree", "facet", or "team formation". The text should
   read like topics from an expert's publication profile.
6. Keep each role_description to 25-55 words. Prefer keyword-rich, specific
   language over long explanatory sentences.
7. Make sibling roles noticeably different. Do not copy the same whole-paper
   summary into every node.
8. evidence_from_abstract should contain 1-3 short spans or clauses. Use an
   empty list only if the abstract lacks support for this node.
9. distinctive_boundary should briefly say what this role includes and excludes
   relative to nearby parent/child/sibling nodes.

{expanded_output_schema()}"""


def build_expanded_prompt_retrieval_dense(paper_id: str, text: str, nodes: Sequence[dict]) -> str:
    return f"""You are writing node-specific expert-search queries for a research team formation system.

Each output role_description will be embedded and compared with experts' historical paper abstracts.
Optimize the text for TOP-1 retrieval of a real author whose prior papers are semantically close to
that node's contribution in THIS paper.

Paper id: {paper_id}
Title/abstract:
{text}

Expanded taxonomy nodes in required output order:
{expanded_node_lines(nodes)}

REQUIREMENTS:
1. Return exactly one JSON object for every input node, in the same order.
2. Write role_description as a dense research-expertise paragraph, 45-75 words.
3. Start each role_description with the node name or root scope, then include paper-specific
   method/problem/application terms copied or closely paraphrased from the title/abstract.
4. For direct FoS nodes, combine the FoS label with the most concrete abstract evidence for that
   facet. Avoid generic duties such as coordination, writing, or project management.
5. For ancestor nodes, do not describe the ancestor label alone. Blend only the listed
   covered_direct_fos descendants into one searchable expertise profile.
6. For __root__, describe the whole paper as a global expert profile with core problem, methods,
   data/application domain, and evaluation/use case when available.
7. Make siblings distinct by choosing different technical nouns, verbs, and evidence clauses.
8. evidence_from_abstract should contain 1-3 short exact spans or clauses. Use an empty list only
   when the abstract is unavailable.
9. Avoid phrases like "This task requires", "responsible for", or "expert who can".

{expanded_output_schema()}"""


def build_expanded_prompt_keyword_query(paper_id: str, text: str, nodes: Sequence[dict]) -> str:
    return f"""You convert each taxonomy node into a compact semantic search query for finding expert authors.

The search target is an expert's historical paper abstract embedding. The best role_description is not
a prose job description; it is a readable query packed with the exact technical terminology an author
would have used in earlier papers.

Paper id: {paper_id}
Title/abstract:
{text}

Expanded taxonomy nodes in required output order:
{expanded_node_lines(nodes)}

REQUIREMENTS:
1. Return exactly one JSON object for every input node, in the same order.
2. role_description must be one sentence of 30-55 words with this content mix:
   node label; covered direct FoS labels if any; paper problem/task; main methods/models/operators;
   application/dataset/evaluation terms if present.
3. Use high-information noun phrases from the title/abstract. Prefer "bipolar fuzzy Hamacher
   aggregation operators, MADM, ERP selection" over generic "decision making methods".
4. Direct nodes should be narrow and keyword-rich. Ancestor nodes should be a union of their covered
   direct descendants, not a broad field survey. Root should be the whole-paper query.
5. Do not add external domain facts, unstated algorithms, or generic collaboration language.
6. Keep siblings lexically different: if two nodes share evidence, emphasize different clauses.
7. key_capabilities should be 2-4 short keyword phrases, not full sentences.
8. evidence_from_abstract should contain 1-3 exact spans or clauses.

{expanded_output_schema()}"""


def build_expanded_prompt_balanced_recall(paper_id: str, text: str, nodes: Sequence[dict]) -> str:
    return f"""You generate paper-grounded expertise profiles for expert-author retrieval.

Goal: maximize recall of real team members from per-node TOP-1 matches while keeping the candidate pool
compact. The descriptions should be specific enough to separate different authors, but broad enough to
match a relevant author's older papers that may not use the exact same title wording.

Paper id: {paper_id}
Title/abstract:
{text}

Expanded taxonomy nodes in required output order:
{expanded_node_lines(nodes)}

REQUIREMENTS:
1. Return exactly one JSON object for every input node, in the same order.
2. role_description should be 35-65 words and include three layers:
   (a) the taxonomy node meaning, (b) the paper-specific contribution, and
   (c) one broader synonym or nearby research phrase if it is clearly implied by the abstract.
3. Direct FoS nodes must stay focused on their own facet. Ancestor nodes must summarize only their
   listed covered_direct_fos descendants. __root__ is a whole-paper author-profile query.
4. Use exact abstract evidence for methods, representations, tasks, datasets, systems, or evaluation.
5. Do not hallucinate unsupported domains from broad ancestor names. If a node label is broad/noisy,
   anchor the text in its covered_direct_fos and abstract evidence.
6. Make parent/child and sibling descriptions retrieval-distinct: one should not be a paraphrase of another.
7. Avoid generic team-formation wording such as "requires an expert", "owner", or "responsibility".
8. evidence_from_abstract should contain 1-3 short exact spans or clauses.

{expanded_output_schema()}"""


def build_expanded_prompt_top1_recall_diverse(
    paper_id: str,
    text: str,
    nodes: Sequence[dict],
) -> str:
    return f"""You generate node-specific expert-search profiles for a per-node TOP-1 team-candidate system.

Evaluation: for each node, the system retrieves exactly ONE best-matching expert from historical-paper
embeddings; then all retrieved experts are unioned and compared with the paper's true authors. Your goal
is to maximize raw recall of true authors, so different nodes should retrieve different plausible
contributors when the paper contains different technical facets.

Paper id: {paper_id}
Title/abstract:
{text}

Expanded taxonomy nodes in required output order:
{expanded_node_lines(nodes)}

REQUIREMENTS:
1. Return exactly one JSON object for every input node, in the same order.
2. Write each role_description as a 40-70 word expert-search profile grounded in the paper.
3. Strongly diversify sibling and parent/child descriptions. Do not let every node describe the same
   whole-paper contribution or the same dominant method. Each node should point toward a different
   plausible author specialty when the abstract supports it.
4. Direct FoS nodes must use the most specific technical evidence for that node. Ancestor nodes should
   combine only their listed covered_direct_fos descendants and should not collapse into the root.
5. The __root__ role should be broad enough to retrieve an overall paper contributor, but it must not
   repeat the same wording as the strongest child node.
6. Prefer concrete signals that appear in author histories: algorithms, mathematical objects, models,
   datasets, systems, materials, biomedical entities, measurement tasks, evaluation settings, and named
   application domains.
7. Include one broader synonym or neighboring phrase only when it is directly implied by the abstract;
   do not hallucinate unstated methods or domains.
8. Avoid generic team-formation wording such as "requires an expert", "responsible for", "owner", or
   "collaboration".
9. evidence_from_abstract should contain 1-3 short exact spans or clauses.

{expanded_output_schema()}"""


def build_expanded_prompt_evidence_facets(
    paper_id: str,
    text: str,
    nodes: Sequence[dict],
) -> str:
    return f"""You turn a paper-local taxonomy into evidence-separated expert retrieval queries.

The downstream system takes each node's role_description, embeds it, retrieves the single nearest
expert-node, and unions those experts. To improve recall, make the node descriptions cover different
evidence facets of the abstract instead of paraphrasing one generic summary.

Paper id: {paper_id}
Title/abstract:
{text}

Expanded taxonomy nodes in required output order:
{expanded_node_lines(nodes)}

REQUIREMENTS:
1. Return exactly one JSON object for every input node, in the same order.
2. For each node, choose a distinct abstract evidence facet first; then write role_description around
   that facet plus the node label. Use 35-65 words.
3. If two nodes share the same evidence sentence, emphasize different clauses: method vs application,
   theory vs experiment, model vs data, system vs evaluation, or domain vs algorithm.
4. Direct FoS nodes should be narrow and concrete. Ancestor nodes should summarize the shared evidence
   among their covered_direct_fos descendants. Root should summarize the full paper but preserve
   terminology from multiple facets, not just the highest-weight node.
5. Do not create unsupported topics from broad ancestor labels. When an ancestor label is noisy, anchor
   it in covered_direct_fos and exact abstract wording.
6. Use author-history-friendly terminology: field names, tasks, methods, equations/operators,
   representations, instruments, datasets, applications, and evaluation criteria.
7. Avoid generic wording such as "expertise in research", "team member", "responsibility", or
   "this task requires".
8. evidence_from_abstract must contain the exact span(s) that guided the description.

{expanded_output_schema()}"""


def build_expanded_prompt(
    paper_id: str,
    text: str,
    nodes: Sequence[dict],
    variant: str = "v2_boundary",
) -> str:
    if variant == "retrieval_dense":
        return build_expanded_prompt_retrieval_dense(paper_id, text, nodes)
    if variant == "keyword_query":
        return build_expanded_prompt_keyword_query(paper_id, text, nodes)
    if variant == "balanced_recall":
        return build_expanded_prompt_balanced_recall(paper_id, text, nodes)
    if variant == "top1_recall_diverse":
        return build_expanded_prompt_top1_recall_diverse(paper_id, text, nodes)
    if variant == "evidence_facets":
        return build_expanded_prompt_evidence_facets(paper_id, text, nodes)
    if variant == "direct_style":
        return build_expanded_prompt_direct_style(paper_id, text, nodes)
    if variant == "v3_retrieval":
        return build_expanded_prompt_v3_retrieval(paper_id, text, nodes)
    return build_expanded_prompt_v2_boundary(paper_id, text, nodes)


def write_jsonl(path: Path, rows: Iterable[dict]) -> None:
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False, separators=(",", ":")))
            f.write("\n")


def read_tasks(args: argparse.Namespace) -> List[dict]:
    rows: List[dict] = []
    name_to_fos_id: dict[str, str] = {}
    id_to_name: dict[str, str] = {}
    id_to_level: dict[str, int] = {}
    child_to_parents: dict[str, set[str]] = {}
    if args.node_scope == "expanded":
        name_to_fos_id, id_to_name, id_to_level = load_fos_maps(Path(args.fos_map))
        child_to_parents = load_child_to_parents(Path(args.taxonomy_edges))
    for obj in iter_jsonl(Path(args.sample_jsonl)):
        paper_id = str(obj.get("id") or obj.get("paper_id") or "").strip()
        text = title_abstract(obj)
        if args.node_scope == "expanded":
            nodes = extract_expanded_nodes(
                obj,
                max_nodes=args.max_nodes_per_paper,
                min_weight=args.min_fos_weight,
                name_to_fos_id=name_to_fos_id,
                id_to_name=id_to_name,
                id_to_level=id_to_level,
                child_to_parents=child_to_parents,
                include_root_role=args.include_root_role,
                ancestor_min_covered_direct=args.ancestor_min_covered_direct,
                expanded_node_policy=args.expanded_node_policy,
            )
            prompt = build_expanded_prompt(
                paper_id,
                text,
                nodes,
                variant=args.expanded_prompt_variant,
            )
        else:
            nodes = extract_nodes(
                obj,
                max_nodes=args.max_nodes_per_paper,
                min_weight=args.min_fos_weight,
            )
            prompt = build_prompt(paper_id, text, nodes)
        if not paper_id or not text or not nodes:
            continue
        rows.append(
            {
                "paper_id": paper_id,
                "title": str(obj.get("title", "")).strip(),
                "year": obj.get("year"),
                "author_count": len(obj.get("authors") or obj.get("team_members") or []),
                "nodes": nodes,
                "prompt": prompt,
            }
        )
        if args.limit > 0 and len(rows) >= args.limit:
            break
    return rows


def build_client(args: argparse.Namespace):
    if args.backend == "template":
        return None

    if args.backend == "together":
        from together import Together

        api_key = args.api_key or os.environ.get("TOGETHER_API_KEY", "")
        return Together(api_key=api_key) if api_key else Together()

    from openai import OpenAI

    api_key = args.api_key or os.environ.get("OPENAI_API_KEY", "")
    return OpenAI(api_key=api_key) if api_key else OpenAI()


def extract_json_array(text: str) -> list:
    cleaned = text.strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
        cleaned = re.sub(r"\s*```$", "", cleaned).strip()
    try:
        obj = json.loads(cleaned)
    except json.JSONDecodeError:
        match = re.search(r"\[.*\]", cleaned, flags=re.DOTALL)
        if not match:
            raise
        obj = json.loads(match.group(0))
    if not isinstance(obj, list):
        raise ValueError("LLM response is not a JSON array")
    return obj


def call_llm(client, args: argparse.Namespace, prompt: str) -> list:
    request = {
        "model": args.model,
        "messages": [
            {"role": "system", "content": system_prompt()},
            {"role": "user", "content": prompt},
        ],
    }
    openai_model = args.backend == "openai" and args.model.lower().startswith("gpt-5")
    if openai_model:
        request["max_completion_tokens"] = args.max_tokens
        if args.temperature != 0.0:
            request["temperature"] = args.temperature
    else:
        request["temperature"] = args.temperature
        request["max_tokens"] = args.max_tokens
    response = client.chat.completions.create(**request)
    return extract_json_array(response.choices[0].message.content)


def call_with_retry(client, args: argparse.Namespace, prompt: str) -> list:
    last_error = None
    for attempt in range(1, args.retry + 1):
        try:
            return call_llm(client, args, prompt)
        except Exception as exc:  # noqa: BLE001 - keep retry diagnostics simple
            last_error = exc
            if attempt >= args.retry:
                raise
            time.sleep(args.retry_sleep)
    raise RuntimeError(f"LLM generation failed: {last_error}")


def template_result(paper: dict, node: dict) -> dict:
    title = str(paper.get("title") or "").strip()
    node_name = str(node.get("node_name") or "").strip()
    role_description = (
        f"Research expertise focused on {node_name} for the paper"
        f" {title!r}. This role covers the node-specific technical facet of the"
        " work, including the relevant methods, domain concepts, experimental"
        " setting, and terminology associated with this node, while leaving"
        " other paper facets to separate task-node roles."
    )
    return {
        "paper_id": paper["paper_id"],
        "node_id": node["node_id"],
        "role_description": role_description,
        "key_capabilities": [
            f"{node_name} research expertise",
            "paper-specific technical interpretation",
            "role-aware team formation evidence matching",
        ],
        "evidence_from_abstract": [title] if title else [],
        "subtree_scope": "whole_paper"
        if node.get("is_root")
        else ("direct_fos" if node.get("is_direct") else "ancestor_subtree"),
        "covered_direct_fos": node.get("direct_descendant_node_names") or [],
        "distinctive_boundary": "Template fallback; no LLM boundary generated.",
    }


def canonical_id(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", value.lower())


def resolve_node_id(node_id: str, expected: Dict[str, dict]) -> str:
    if node_id in expected:
        return node_id

    canonical = canonical_id(node_id)
    canonical_matches = [
        expected_id
        for expected_id in expected
        if canonical_id(expected_id) == canonical
    ]
    if len(canonical_matches) == 1:
        return canonical_matches[0]

    scored = [
        (difflib.SequenceMatcher(a=canonical, b=canonical_id(expected_id)).ratio(), expected_id)
        for expected_id in expected
    ]
    scored.sort(reverse=True)
    if scored and scored[0][0] >= 0.9 and (len(scored) == 1 or scored[0][0] > scored[1][0]):
        return scored[0][1]

    raise KeyError(node_id)


def normalize_result(obj: dict, paper: dict, input_nodes: Sequence[dict]) -> dict:
    expected = {node["node_id"]: node for node in input_nodes}
    raw_node_id = str(obj.get("node_id", "")).strip()
    try:
        node_id = resolve_node_id(raw_node_id, expected)
    except KeyError:
        raise ValueError(f"Unexpected node_id for paper {paper['paper_id']}: {raw_node_id}")
    role_description = str(obj.get("role_description") or "").strip()
    if not role_description:
        raise ValueError(f"Missing role_description for paper={paper['paper_id']} node={node_id}")
    key_capabilities = obj.get("key_capabilities")
    evidence = obj.get("evidence_from_abstract")
    node = expected[node_id]
    return {
        "id": f"{paper['paper_id']}::{node_id}",
        "paper_id": paper["paper_id"],
        "node_id": node_id,
        "node_name": node["node_name"],
        "node_level": node.get("node_level", "fos"),
        "node_weight": node["node_weight"],
        "is_root": bool(node.get("is_root", False)),
        "is_direct": bool(node.get("is_direct", False)),
        "ancestor_depth": node.get("ancestor_depth", 0),
        "tree_parent_node_ids": node.get("tree_parent_node_ids") or [],
        "direct_descendant_node_ids": node.get("direct_descendant_node_ids") or [],
        "direct_descendant_node_names": node.get("direct_descendant_node_names") or [],
        "role_description": role_description,
        "key_capabilities": [str(x) for x in key_capabilities]
        if isinstance(key_capabilities, list)
        else [],
        "evidence_from_abstract": [str(x) for x in evidence]
        if isinstance(evidence, list)
        else [],
        "subtree_scope": str(obj.get("subtree_scope") or "").strip(),
        "covered_direct_fos": [str(x) for x in obj.get("covered_direct_fos")]
        if isinstance(obj.get("covered_direct_fos"), list)
        else [],
        "distinctive_boundary": str(obj.get("distinctive_boundary") or "").strip(),
    }


def main() -> None:
    args = parse_args()
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    prompt_rows = read_tasks(args)
    prompts_path = out_dir / "stage1_task_node_role_prompts.jsonl"
    write_jsonl(prompts_path, prompt_rows)
    print(f"prompts={prompts_path}")
    print(
        f"papers={len(prompt_rows)} nodes={sum(len(row['nodes']) for row in prompt_rows)}",
        flush=True,
    )
    (out_dir / "run_config.json").write_text(
        json.dumps(
            {
                "sample_jsonl": args.sample_jsonl,
                "out_dir": args.out_dir,
                "limit": args.limit,
                "max_nodes_per_paper": args.max_nodes_per_paper,
                "min_fos_weight": args.min_fos_weight,
                "node_scope": args.node_scope,
                "expanded_node_policy": args.expanded_node_policy,
                "expanded_prompt_variant": args.expanded_prompt_variant,
                "include_root_role": args.include_root_role,
                "ancestor_min_covered_direct": args.ancestor_min_covered_direct,
                "fos_map": args.fos_map,
                "taxonomy_edges": args.taxonomy_edges,
                "generate": args.generate,
                "backend": args.backend,
                "model": args.model,
                "temperature": args.temperature,
                "max_tokens": args.max_tokens,
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    if not args.generate:
        print("dry_run=1")
        return

    desc_path = out_dir / "stage1_task_node_role_descriptions.jsonl"
    raw_path = out_dir / "stage1_task_node_role_descriptions_raw_by_paper.jsonl"

    done_papers: set[str] = set()
    if desc_path.exists():
        for row in iter_jsonl(desc_path):
            paper_id = str(row.get("paper_id", "")).strip()
            if paper_id:
                done_papers.add(paper_id)
    if done_papers:
        print(f"resume=1 already_done_papers={len(done_papers)}")

    pending = [row for row in prompt_rows if row["paper_id"] not in done_papers]
    client = build_client(args)
    print(f"to_generate={len(pending)} workers={args.workers}", flush=True)

    import threading

    write_lock = threading.Lock()
    counter = {"done": 0}
    failures: List[str] = []

    def process(row: dict) -> None:
        try:
            if args.backend == "template":
                results = [template_result(row, node) for node in row["nodes"]]
            else:
                results = call_with_retry(client, args, row["prompt"])
            normalized = [normalize_result(obj, row, row["nodes"]) for obj in results]
            if len(normalized) != len(row["nodes"]):
                raise ValueError(
                    f"Expected {len(row['nodes'])} node outputs, got {len(normalized)}"
                )
        except Exception as exc:  # noqa: BLE001 - isolate one paper failure
            with write_lock:
                failures.append(row["paper_id"])
                print(f"FAILED paper={row['paper_id']} error={exc}", flush=True)
            return

        with write_lock:
            raw_out.write(
                json.dumps(
                    {"paper_id": row["paper_id"], "results": results},
                    ensure_ascii=False,
                    separators=(",", ":"),
                )
                + "\n"
            )
            raw_out.flush()
            for record in normalized:
                desc_out.write(
                    json.dumps(record, ensure_ascii=False, separators=(",", ":")) + "\n"
                )
            desc_out.flush()
            counter["done"] += 1
            if args.progress_every > 0 and (
                counter["done"] == len(pending) or counter["done"] % args.progress_every == 0
            ):
                print(
                    f"progress={counter['done']}/{len(pending)} paper={row['paper_id']} nodes={len(normalized)}",
                    flush=True,
                )

    with desc_path.open("a", encoding="utf-8") as desc_out, raw_path.open(
        "a", encoding="utf-8"
    ) as raw_out:
        if args.workers <= 1:
            for row in pending:
                process(row)
                if args.sleep_seconds > 0:
                    time.sleep(args.sleep_seconds)
        else:
            with ThreadPoolExecutor(max_workers=args.workers) as pool:
                for _ in pool.map(process, pending):
                    pass

    print(f"raw={raw_path}")
    print(f"descriptions={desc_path}")
    if failures:
        print(f"failed_papers={len(failures)} rerun same command to resume")


if __name__ == "__main__":
    main()
